keys:
  - &arindamukawlas age120kv7ljdp0k2dgx9pg42sp0vwepzgdl882wa4ygkax4r9eqf7p2qypz68a
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *arindamukawlas
